name: ddev-node
networks:
  ddev_default:
    external: true
    name: ddev_default
  default:
    name: ddev-node_default
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mariadb-10.4:v1.20.0
        gid: "1000"
        uid: "1000"
        username: nkoporec
      context: /home/nkoporec/work/tmp/node/.ddev/.dbimageBuild
      dockerfile: Dockerfile
    container_name: ddev-node-db
    environment:
      COLUMNS: "346"
      DDEV_DATABASE: mariadb:10.4
      DDEV_HOSTNAME: node.ddev.site
      DDEV_PHP_VERSION: "8.1"
      DDEV_PRIMARY_URL: https://node.ddev.site
      DDEV_PROJECT: node
      DDEV_PROJECT_TYPE: drupal10
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SITENAME: node
      DDEV_TLD: ddev.site
      DOCKER_IP: 127.0.0.1
      GOARCH: amd64
      GOOS: linux
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      IS_DDEV_PROJECT: "true"
      LINES: "69"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/node-db/mysql_history
      MYSQL_PWD: db
      PGDATABASE: db
      PGHOST: localhost
      PGPASSWORD: db
      PGUSER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: ""
      USER: nkoporec
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m0s
      timeout: 2m0s
    hostname: node-db
    image: drud/ddev-dbserver-mariadb-10.4:v1.20.0-node-built
    labels:
      com.ddev.app-type: drupal10
      com.ddev.approot: /home/nkoporec/work/tmp/node
      com.ddev.platform: ddev
      com.ddev.site-name: node
    networks:
      ddev_default: null
      default: null
    ports:
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      target: 3306
    restart: "no"
    stop_grace_period: 1m0s
    user: 1000:1000
    volumes:
    - source: database
      target: /var/lib/mysql
      type: volume
      volume:
        nocopy: true
    - bind:
        create_host_path: true
      source: /home/nkoporec/work/tmp/node/.ddev
      target: /mnt/ddev_config
      type: bind
    - bind:
        create_host_path: true
      source: /home/nkoporec/work/tmp/node/.ddev/db_snapshots
      target: /mnt/snapshots
      type: bind
    - source: ddev-global-cache
      target: /mnt/ddev-global-cache
      type: volume
      volume: {}
    working_dir: /home/nkoporec
  dba:
    container_name: ddev-node-dba
    environment:
      HTTP_EXPOSE: 8036:8036
      HTTPS_EXPOSE: 8037:8036
      PMA_PASSWORD: root
      PMA_USER: root
      TZ: ""
      UPLOAD_LIMIT: 1024M
      VIRTUAL_HOST: node.ddev.site
    expose:
    - "80"
    healthcheck:
      interval: 2m0s
      retries: 1
      timeout: 2s
    hostname: node-dba
    image: phpmyadmin:5
    labels:
      com.ddev.app-type: drupal10
      com.ddev.approot: /home/nkoporec/work/tmp/node
      com.ddev.platform: ddev
      com.ddev.site-name: node
    networks:
      ddev_default: null
      default: null
    restart: "no"
    working_dir: /root
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.20.0
        gid: "1000"
        uid: "1000"
        username: nkoporec
      context: /home/nkoporec/work/tmp/node/.ddev/.webimageBuild
      dockerfile: Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-node-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      COLUMNS: "346"
      DDEV_DATABASE: mariadb:10.4
      DDEV_DOCROOT: web
      DDEV_FILES_DIR: /var/www/html/web/sites/default/files
      DDEV_HOSTNAME: node.ddev.site
      DDEV_PHP_VERSION: "8.1"
      DDEV_PRIMARY_URL: https://node.ddev.site
      DDEV_PROJECT: node
      DDEV_PROJECT_TYPE: drupal10
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SITENAME: node
      DDEV_TLD: ddev.site
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: "1"
      DRUSH_OPTIONS_URI: https://node.ddev.site
      GOARCH: amd64
      GOOS: linux
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTP_EXPOSE: 80:80,8025:8025
      HTTPS_EXPOSE: 443:80,8026:8025
      IS_DDEV_PROJECT: "true"
      LINES: "69"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/node-web/mysql_history
      MYSQL_PWD: db
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: db
      PGUSER: db
      PHP_IDE_CONFIG: serverName=node.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ""
      USER: nkoporec
      VIRTUAL_HOST: node.ddev.site
    external_links:
    - ddev-router:node.ddev.site
    extra_hosts:
      host.docker.internal: 172.17.0.1
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m0s
      timeout: 2m0s
    hostname: node-web
    image: drud/ddev-webserver:v1.20.0-node-built
    labels:
      com.ddev.app-type: drupal10
      com.ddev.approot: /home/nkoporec/work/tmp/node
      com.ddev.platform: ddev
      com.ddev.site-name: node
    networks:
      ddev_default: null
      default: null
    ports:
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      target: 80
    - host_ip: 127.0.0.1
      mode: ingress
      protocol: tcp
      target: 443
    restart: "no"
    user: 1000:1000
    volumes:
    - consistency: cached
      source: ../
      target: /var/www/html
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/nkoporec/work/tmp/node/.ddev
      target: /mnt/ddev_config
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/nkoporec/work/tmp/node/.ddev/xhprof
      target: /usr/local/bin/xhprof
      type: bind
    - source: ddev-global-cache
      target: /mnt/ddev-global-cache
      type: volume
      volume: {}
    - source: ddev-ssh-agent_socket_dir
      target: /home/.ssh-agent
      type: volume
      volume: {}
    working_dir: /var/www/html/
volumes:
  database:
    external: true
    name: node-mariadb
  ddev-global-cache:
    external: true
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
